FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000 5001 5002

# O comando será sobrescrito pelo docker-compose.yml para cada container
CMD ["python", "centrais_postos/central_posto.py"] 